service: cmu-timetable-proxy

provider:
  name: google
  runtime: nodejs
  project: cmu-timetable-proxy
  credentials: ~/.gcloud/cmu-timetable-proxy-keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  enrollment:
    handler: enrollment
    events:
      - http: path
  course:
    handler: course
    events:
      - http: path
